import { SpeedInsights } from "@vercel/speed-insights/next"
import { exo2, exo2Italic, montserrat, montserratItalic } from './fonts'
import "./globals.css";
import Header from "./components/layout/Header/Header";
import Footer from "./components/layout/Footer/Footer";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import YandexMetrikaContainer from "./components/layout/YandexMetrikaContainer/YandexMetrikaContainer";
config.autoAddCss = false
const analyticsEnabled = !!(process.env.CURRENT_DOMAIN === "https://funduk.studio");
// const analyticsEnabled = true;


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <head>
        <meta
          name="yandex-verification"
          content={process.env.WEBMASTER_METATAG}
      />
      </head>
      <body className={`${exo2.variable} ${exo2Italic.variable} ${montserrat.variable} ${montserratItalic.variable}`}>
        <Header/>
        {children}
        <Footer/>
        <SpeedInsights/>
        <YandexMetrikaContainer enabled={analyticsEnabled} />
      </body>
    </html>
  );
}
