import { SpeedInsights } from "@vercel/speed-insights/next"
import { exo2, exo2Italic, montserrat, montserratItalic } from './fonts'
import "./globals.css";
import Header from "./components/layout/Header/Header";
import Footer from "./components/layout/Footer/Footer";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${exo2.variable} ${exo2Italic.variable} ${montserrat.variable} ${montserratItalic.variable}`}>
        <Header/>
        {children}
        <Footer/>
        <SpeedInsights/>
      </body>
    </html>
  );
}
